### ISSUE TITLE
能不能出个一步一步编译出debian系统的教程，带gpu的，buildroot下网络跟摆设一样

### ISSUE THREAD

**Issue by xiaguangbo** [starfive-tech/VisionFive2#100]
buildroot装个其他工具累死人，要用apt

**Comment by MichaelZhuxx** [comment]
https://rvspace.org/en/project/Building_StarFive_Debian_Image

**Comment by xiaguangbo** [comment]
@MichaelZhuxx  thank，I can hardly find a clue to this article
