### ISSUE TITLE
Way from SDK to IMG

### ISSUE THREAD

**Issue by dtometzki** [starfive-tech/VisionFive2#12]
Hello together,

is there a way or description how we move new features from SDK to an Image for example the new released starfive image. 
For example i can build in SDK new kernel options or drivers but i dont know how to move it to the image. 
Here is such example to move new kernel feuter to the fedora image https://github.com/starfive-tech/linux

But it isnt usable for starvision2 ?

Best regards
Damian

**Comment by andyhu-stf** [comment]
@dtometzki , Now for the JH110 visonfive 2 board, we can support debian. Do you mean how to move the new feature kernel to debian? 
If so, from my experience, you can run the below:
```
cd work/linux
export PATH=../buildroot_initramfs/host/bin:$PATH
make ARCH=riscv CROSS_COMPILE=riscv64-linux- -j8 bindeb-pkg
```
Then the below files will be generated under work/
linux-headers-5.15.0_5.15.0-1_riscv64.deb
linux-image-5.15.0_5.15.0-1_riscv64.deb
linux-libc-dev_5.15.0-1_riscv64.deb

you can copy these deb files to the running debian system, and install `dpkg -i *.deb`

**Comment by dtometzki** [comment]
Hello @andyhu-stf,

many thanks for your help. It works perfekt. What is the reason why we dont us the branch JH7110_VisionFive2_upstream in SDK ? 
Is it possible to use and test it ?

Merry Christmas
Damian

**Comment by MichaelZhuxx** [comment]
@dtometzki JH7110_VisionFive2_upstream is just for upstream which is only contain minimal driver system, like pinctrl, clock tree, plic, clint, serial port, sdio etc. Now we are submitting patches gradually.

**Comment by dtometzki** [comment]
Thanks a lot
