### ISSUE TITLE
output from serial port are all unreadable characters, COM port settings seems no problem.

### ISSUE THREAD

**Issue by sharpbladepan** [starfive-tech/VisionFive2#16]
![com_para](https://user-images.githubusercontent.com/3395150/209360701-0bd74f32-1065-4f3e-be4e-7a4f355fa241.png)

this is comm parameters.

I've changed two cables, two notebooks with three OS ( win11, win10, majaro) but with no luck  :(

**Comment by sharpbladepan** [comment]
Might be voltage level mismatch between the cable and StarFive2
Waiting for my new convert-module arriving...

**Comment by MichaelZhuxx** [comment]
@sharpbladepan what's voltage of your serial board. should be 3.3v

**Comment by sharpbladepan** [comment]
Yes, after using my new USB-TTL module, it's OK now.
Thank you!

**Comment by sharpbladepan** [comment]
Yes, after using my new USB-TTL module, it's OK now.
Thank you!

**Comment by sharpbladepan** [comment]
close it!
