### ISSUE TITLE
/proc/mtd no such file or directory

### ISSUE THREAD

**Issue by MiMillieuh** [starfive-tech/VisionFive2#27]
Hello, 

I've recived my boards and I can't update them since the mtd partitions aren't available on the 55 version of debian.

So how should I update my board ?

(Also why is it only using 4GB since I have 8 GB)

**Comment by MiMillieuh** [comment]
I figured it out, 

There are no clear guide to get it working so I'll try to explain how I did it :

- Download this image : https://github.com/starfive-tech/VisionFive2/releases/download/VF2_v2.5.0/sdcard.img
- Flash it on your sdcard 
- Copy the latest files of "visionfive2_fw_payload.img" and "u-boot-spl.bin.normal.out" in your root folder on the sdcard
- login via ssh and use these commands : `flashcp -v u-boot-spl.bin.normal.out /dev/mtd0` `flashcp -v visionfive2_fw_payload.img /dev/mtd1`

To be clear the hard part was to understand that the 55 image has no mtd support but it was the one recommended to update.

**Comment by liayan** [comment]
thanks for the document. 
sdcard is the image for buildroot, it has the mtd partition while 55 image is a full linux image that do not have mtd partition.
