### ISSUE TITLE
Flashed v2.10.4, image 69 won't boot anymore

### ISSUE THREAD

**Issue by 2bigO** [starfive-tech/VisionFive2#29]
Hi,

I just flashed the latest firmware [VisionFive2 Software v2.10.4](https://github.com/starfive-tech/VisionFive2/releases/tag/VF2_v2.10.4), the `Debian 69` image won't boot anymore, also no blinking green LED.

Can you please advise?

**Comment by MichaelZhuxx** [comment]
yes, please use new Debian image 202302, link: https://debian.starfivetech.com/.
