### ISSUE TITLE
Can not upgrade to firmware v2.11.5

### ISSUE THREAD

**Issue by carlosgonz0** [starfive-tech/VisionFive2#37]
It say: won't  fit in mtd0, seems not space in there.
I was fine to burn v2.11.4 but not v2.11.5 because not space enough.

thanks

**Comment by MichaelZhuxx** [comment]
May I know you how to upgrade the firmware(uboot and spl)? based on Debian image 202302, right? yes. it's true. as the size of SPL is larger than before. here is an explanation: https://github.com/starfive-tech/VisionFive2/releases#:~:text=Expand%20the%20MTD0%20partition%20size%20in%20QSPI%2Dflash%20and%20increase%20the%20buffer%20size%20of%20spl_tool%20after%20enabling%20vout%20module%20in%20U%2DBoot%3B

so there are three ways to update the spl:
1. tftp under uboot and sf update it;
2. flashcp in kernel with v2.11.5 sdimage;
3. flashcp in debian image 202303;(to be released)

**Comment by carlosgonz0** [comment]
Thanks @MichaelZhuxx, yes i using Debian 202302. Great that will be possible in Debian   202303.
- So to using v2.11.5 sdimage i need move some hardware switches?
- v2.11.5 sdimage work just for HDMI or serial UART?

**Comment by MichaelZhuxx** [comment]
@carlosgonz0 sdimage is based on buildroot rootfs. so no desktop window shows up, only framebuffer console. 
you can login it by ssh over ethernet or serial uart to input the flashcp command for updating firmware.

**Comment by carlosgonz0** [comment]
Thanks
