### ISSUE TITLE
soft_3rdpart/spl_tool/create_{hdr,sbl} are amd64 binaries

### ISSUE THREAD

**Issue by kth5** [starfive-tech/VisionFive2#4]
The current SDK cannot be built on non-x86_64 Linux systems since some shipped programs cannot be executed elsewhere. In adition there is no source available... This is yet another unfortunate problem for a SDK targetting a "open source" SBC.

I'm building on `ppc64le` and got through most of the build already but I'm stuck here. `binfmt` tries to rescue me but I don't have a x86_64 chroot for it to work.

![image](https://user-images.githubusercontent.com/1784992/207868958-2a3858a0-a52f-483c-a8fc-70ebe3427224.png)

**Comment by andyhu-stf** [comment]
Hi @kth5, the `create_sbl` and `create_hdr` under `soft_3rdpart/spl_tool/` are the starfive proprietary uboot spl tool. These binary will generate the target `u-boot-spl.bin.normal.out`. They are not open source and provided as the executable binary file on `x86 linux` platform. 

Now we still have not support to build the sdk code on `ppc64le` platform yet. Maybe we can support it later.

And if you are not interested in the `u-boot-spl.bin.normal.out`, you can modify the Makefile
`all: check_arg $(fit) $(vfat_image) $(uboot_fit) $(spl_bin_normal_out)`
to
`all: check_arg $(fit) $(vfat_image) $(uboot_fit)`
Then you can continue to try building on `ppc64le` platform

**Comment by NickCao** [comment]
You may use https://github.com/NickCao/starfive-tools/blob/master/spl_tool/create_sbl as a replacement.

**Comment by MichaelZhuxx** [comment]
I think this issue could be closed as we open source the spl tool https://github.com/starfive-tech/Tools/tree/master/spl_tool
