### ISSUE TITLE
Unable to upload recovery bootloader

### ISSUE THREAD

**Issue by matsbror** [starfive-tech/VisionFive2#42]
One of the cards I have won’t boot so I thought I should flash the bootloader reovery over UART. I set the dip switches so I get the CCCCC on the serial port as per the instructions. I use minicom to transfer the recovery file which is initiated correctly but I get a `CRC Error` and then the CCCC continues. Any help is appreciated.

**Comment by MichaelZhuxx** [comment]
maybe this link https://github.com/starfive-tech/Tools/issues/3 will help on this

**Comment by matsbror** [comment]
Thanks, I tried this once, but here are more details and I will try it.

**Comment by matsbror** [comment]
It's stuck int `Waiting for bootloader mode on /dev/ttyUSB0...`

**Comment by matsbror** [comment]
I switched to the vf2 branch and now this happened:
```
mats@ubuntu-Latitude-9510:~/riscv-debian-images$ sudo ./vf2-recover -D /dev/ttyUSB0 -r jh7110-recovery-20230322.bin 
Waiting for bootloader mode on /dev/ttyUSB0...
CCCCCCCCC
Bootloader mode active

Uploading recovery binary...
	Waiting for XMODEM request[C]...
	Sending jh7110-recovery-20230322.bin 
[########################################] 100%  173118/173118 Bytes
CRC Error, Try again
```

**Comment by matsbror** [comment]
I still am not able to use the recovery image over the serial port but I managed to flash a new bootloader through booting from QSPI.

**Comment by MichaelZhuxx** [comment]
please refer to this guide https://doc-en.rvspace.org/VisionFive2/Quick_Start_Guide/VisionFive2_SDK_QSG/recovering_bootloader%20-%20vf2.html
