### ISSUE TITLE
Boot failure

### ISSUE THREAD

**Issue by matsbror** [starfive-tech/VisionFive2#43]
This ie the output I get on the serial port when trying to boot from SD-card:
```
dwmci_s: Response Timeout.
BOOT fail,Error is 0xffffffff
dwmci_s: Response Timeout.
BOOT fail,Error is 0xffffffff
```

I took that as an indication that the regular boot loader is not working so I tried to do a recovery https://github.com/starfive-tech/VisionFive2/issues/42.

However maybe it is a more serious issue. Can someone tell?

**Comment by MichaelZhuxx** [comment]
please push the reset button to try to reboot

**Comment by matsbror** [comment]
I just get another 
```
dwmci_s: Response Timeout.
BOOT fail,Error is 0xffffffff
```

then

**Comment by MichaelZhuxx** [comment]
regarding to your mentioned above the booting failure when boot the system from SD card directly, you do not need do a recovery way since that is the way for boot from QSPI flash and its data was broken in some way.

**Comment by matsbror** [comment]
> regarding to your mentioned above the booting failure when boot the system from SD card directly, you do not need do a recovery way since that is the way for boot from QSPI flash and its data was broken in some way.

Thanks! However, I am sorry, but I do not understand what you are writing. The above error is what I get when I try to boot from SD. I have reported in another issue (https://github.com/starfive-tech/VisionFive2/issues/42) my troubles when trying to do the recovery of the boot loader.

**Comment by leifhelm** [comment]
I get this error when I try to boot without an SD card inserted.

**Comment by matsbror** [comment]
I got the card to boot by flashing a new bootloader so I am closing this issue.
