### ISSUE TITLE
u-boot 2.10.4 and 2.11.5 won't fit

### ISSUE THREAD

**Issue by Andrejs4** [starfive-tech/VisionFive2#45]
I bricked my StarFive2 v1.2A (super early bird) when tried to write u-boot with dd.
With SD card recovery I was able to write only version 2.8.0

u-boot-spl.bin.normal.out 129.1K 

# flashcp -v u-boot-spl.bin.normal.out /dev/mtd0
u-boot-spl.bin.normal.out won't fit into /dev/mtd0!

**Comment by MichaelZhuxx** [comment]
please flash the latest debian image(202303) into SD and boot it from SD directly(switch the boot mode to sdio)

**Comment by Andrejs4** [comment]
Thanks, worked!
There is no need to upgrade the firmware anymore.
Sorry I didn't understood it sooner.
