### ISSUE TITLE
build of SDK failed - Source img-gpu-powervr-bin-1.17.6210866.tar.gz not found

### ISSUE THREAD

**Issue by dtometzki** [starfive-tech/VisionFive2#5]
Hello together,

i try to build the SDK but i get the following error: 
ERROR: img-gpu-powervr-bin-1.17.6210866.tar.gz has wrong sha256 hash:
ERROR: expected: 8ef5eba77c776e0d4444d819e12c64bfa8eee0ae2cdf90b6eb7a3a9df7bd7ef2
ERROR: got     : c242d40d0f7ae9733f37df2720ef61621c578c4f3e630c8456b92c206720f2c8
ERROR: Incomplete download, or man-in-the-middle (MITM) attack
wget --passive-ftp -nd -t 3 -O '/home/damian/kernel/misc/riscv/VisionFive2/work/buildroot_initramfs/build/.img-gpu-powervr-bin-1.17.6210866.tar.gz.qP0g3t/output' 'http://sources.buildroot.net/img-gpu-powervr/img-gpu-powervr-bin-1.17.6210866.tar.gz' 
--2022-12-15 20:04:49--  http://sources.buildroot.net/img-gpu-powervr/img-gpu-powervr-bin-1.17.6210866.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 2606:4700:20::681a:25, 2606:4700:20::ac43:4838, 2606:4700:20::681a:125, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|2606:4700:20::681a:25|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-15 20:04:50 ERROR 404: Not Found.

Any ideas when the source available again ?

Best regards
Damian

**Comment by m00dawg** [comment]
I am also getting this error.

**Comment by kth5** [comment]
See #2  , it's missing `git-lfs` enablement. Just installing `git-lfs` isn't enough.

**Comment by omac777** [comment]
I'm confirming 
http://sources.buildroot.net/img-gpu-powervr/img-gpu-powervr-bin-1.17.6210866.tar.gz
is not there.

It's directory is not there either:
http://sources.buildroot.net/img-gpu-powervr/

There's another directory powervr but it's empty as well:
http://sources.buildroot.net/powervr/

By the way I googled for this file img-gpu-powervr-bin-1.17.6210866.tar.gz
but no hits were returned.  I also googled for img-gpu-powervr-bin nothing returned either.

**Comment by Jenot** [comment]
Download files from here: https://github.com/starfive-tech/VisionFive2/tree/JH7110_VisionFive2_devel/soft_3rdpart/IMG_GPU/out

**Comment by ycat3** [comment]
I downloaded files as you say, however build failed in the middle.
---------------------------------------------------------------------------------------------------------
-- Build files have been written to: /home/mycat/VisionFive2/work/buildroot_initramfs/build/ispsdk-2.0.0/buildroot-build
>>> ispsdk 2.0.0 Building
PATH="/home/mycat/VisionFive2/work/buildroot_initramfs/host/bin:/home/mycat/VisionFive2/work/buildroot_initramfs/host/sbin:/home/mycat/.local/bin:/home/mycat/.cargo/bin:/home/mycat/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin"  /usr/bin/make   -C /home/mycat/VisionFive2/work/buildroot_initramfs/build/ispsdk-2.0.0//buildroot-build
[  0%] Built target Mantis_RegistersDefinitions
[  1%] Building C object sensorapi/CMakeFiles/SensorApi.dir/src/sensorapi/sensor_phy.c.o
[  4%] Building C object sensorapi/CMakeFiles/SensorApi.dir/src/sensors/ov4689mipi.c.o
[  4%] Building C object sensorapi/CMakeFiles/SensorApi.dir/src/sensors/imx219mipi.c.o
[  6%] Building C object sensorapi/CMakeFiles/SensorApi.dir/src/sensorapi/sensorapi.c.o
[  7%] Building C object sensorapi/CMakeFiles/SensorApi.dir/src/sensors/sc2235dvp.c.o
[  9%] Linking C static library libSensorApi.a
[  9%] Built target SensorApi
[ 12%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_reg_test.c.o
[ 18%] Building C object startfive_apps/StarFiveServer/CMakeFiles/StarFiveServer.dir/src/broadcast_main.c.o
[ 18%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/ISP_test.c.o
[ 18%] Building C object test_apps/stf_isp_test/CMakeFiles/stf_isp_test.dir/src/convert.c.o
[ 19%] Building C object test_apps/stf_isp_test/CMakeFiles/stf_isp_test.dir/src/yuv.c.o
[ 19%] Building C object test_apps/stf_isp_test/CMakeFiles/stf_isp_test.dir/src/common.c.o
[ 18%] Building C object test_apps/stf_isp_ctrl/CMakeFiles/stf_isp_ctrl.dir/src/stf_isp_ctrl.c.o
[ 24%] Building C object startfive_apps/StarFiveServer/CMakeFiles/StarFiveServer.dir/src/main.c.o
[ 24%] Building C object test_apps/stf_isp_test/CMakeFiles/stf_isp_test.dir/src/stf_isp_test.c.o
[ 25%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_mem_test.c.o
[ 27%] Building C object startfive_apps/StarFiveServer/CMakeFiles/StarFiveServer.dir/src/ispc_main.c.o
[ 27%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_isp_base_test.c.o
[ 28%] Building C object test_apps/stf_isp_test/CMakeFiles/stf_isp_test.dir/src/stf_log.c.o
[ 30%] Building C object test_apps/stf_isp_test/CMakeFiles/stf_isp_test.dir/src/stf_drm.c.o
[ 31%] Building C object test_apps/stf_isp_test/CMakeFiles/stf_isp_test.dir/src/stf_framebuffer.c.o
[ 33%] Building C object startfive_apps/StarFiveServer/CMakeFiles/StarFiveServer.dir/src/rtp_enc.c.o
[ 34%] Building C object startfive_apps/StarFiveServer/CMakeFiles/StarFiveServer.dir/src/rtsp_demo.c.o
[ 36%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_mod_sud_test.c.o
[ 37%] Building C object startfive_apps/StarFiveServer/CMakeFiles/StarFiveServer.dir/src/rtsp_main.c.o
[ 39%] Building C object startfive_apps/StarFiveServer/CMakeFiles/StarFiveServer.dir/src/rtsp_msg.c.o
[ 40%] Building C object test_apps/stf_isp_test/CMakeFiles/stf_isp_test.dir/src/stf_v4l2.c.o
[ 42%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_mod_csi_in_test.c.o
[ 43%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_mod_cbar_test.c.o
[ 45%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_mod_crop_test.c.o
[ 46%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_mod_dc_test.c.o
[ 48%] Building C object startfive_apps/StarFiveServer/CMakeFiles/StarFiveServer.dir/src/rtsp_utils.c.o
[ 50%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_mod_dec_test.c.o
[ 51%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_mod_oba_test.c.o
[ 53%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_mod_obc_test.c.o
[ 54%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_mod_lcbq_test.c.o
[ 56%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_mod_sc_test.c.o
[ 57%] Building C object startfive_apps/StarFiveServer/CMakeFiles/StarFiveServer.dir/src/tinycthread.c.o
[ 59%] Linking C executable stf_isp_test
[ 60%] Building C object test_apps/ISP_test/CMakeFiles/ISP_test.dir/src/test/ISP_mod_dump_test.c.o
[ 62%] Building C object startfive_apps/StarFiveServer/CMakeFiles/StarFiveServer.dir/src/tuning_base.c.o
/home/mycat/VisionFive2/work/buildroot_initramfs/host/lib/gcc/riscv64-buildroot-linux-gnu/10.3.0/../../../../riscv64-buildroot-linux-gnu/bin/ld:../../../libispsdk/libStfIncludes.a: file format not recognized; treating as linker script
/home/mycat/VisionFive2/work/buildroot_initramfs/host/lib/gcc/riscv64-buildroot-linux-gnu/10.3.0/../../../../riscv64-buildroot-linux-gnu/bin/ld:../../../libispsdk/libStfIncludes.a:1: syntax error
collect2: error: ld はステータス 1 で終了しました

**Comment by dtometzki** [comment]
Hello together,

i tried again with git-lfs installed and now the build was successfully. 
thanks
Damian

**Comment by omac777** [comment]
> Download files from here: https://github.com/starfive-tech/VisionFive2/tree/JH7110_VisionFive2_devel/soft_3rdpart/IMG_GPU/out

I have a problem with this.  It doesn't conform to the existing documentation in the quick start guide nor the sdk quick start guide.

The files should be available sticking to the original build instructions.  We shouldn't be having to do download it from a different location.  Others will be experiencing this very same pain so it should be corrected at the source rather than providing a workaround.

**Comment by andyhu-stf** [comment]
> 

Yes, I agree it. The IMG GPU user space code could not open source from the GPU IP vendor, so we provide the binary tarball. Considering the big size for the tarball, we do git push through git lfs. If your PC environment support git lfs, you can download all the code using the git clone command.
