### ISSUE TITLE
kernel tag VF2_v3.0.4 crashes on boot

### ISSUE THREAD

**Issue by st3g4n0** [starfive-tech/VisionFive2#53]
I compile the kernel with tag VF2_v3.0.4 and when boot it i got:  [drm:inno_hdmi_bind] *ERROR* cannot get hpd gpio property
and a kernel panic.

> [    0.000000] Linux version 5.15.0+ (user@starfive) (gcc (Debian 12.2.0-10) 12.2.0, GNU ld (GNU Binutils for Debian) 2.39.50.20221224) #2 SMP Mon Jun 5 20:22:46 UTC 2023
[    0.000000] OF: fdt: Ignoring memory range 0x40000000 - 0x40200000
[    0.000000] Machine model: StarFive VisionFive V2
[    0.000000] earlycon: uart0 at MMIO32 0x0000000010000000 (options '115200')
[    0.000000] printk: bootconsole [uart0] enabled
[    0.000000] efi: UEFI not found.
[    0.000000] Reserved memory: created CMA memory pool at 0x0000000080000000, size 512 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   DMA32    [mem 0x0000000040200000-0x00000000ffffffff]
[    0.000000]   Normal   [mem 0x0000000100000000-0x000000023fffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000040200000-0x00000000c010ffff]
[    0.000000]   node   0: [mem 0x00000000c0110000-0x00000000c01fffff]
[    0.000000]   node   0: [mem 0x00000000c0200000-0x000000023fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000040200000-0x000000023fffffff]
[    0.000000] SBI specification v1.0 detected
[    0.000000] SBI implementation ID=0x1 Version=0x10002
[    0.000000] SBI TIME extension detected
[    0.000000] SBI IPI extension detected
[    0.000000] SBI RFENCE extension detected
[    0.000000] SBI SRST extension detected
[    0.000000] SBI v0.2 HSM extension detected
[    0.000000] CPU with hartid=0 is not available
[    0.000000] CPU with hartid=0 is not available
[    0.000000] riscv: base ISA extensions acdfim
[    0.000000] riscv: ELF capabilities acdfim
[    0.000000] percpu: Embedded 18 pages/cpu s34024 r8192 d31512 u73728
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 2067975
[    0.000000] Kernel command line: root=/dev/mmcblk1p4 root=/dev/mmcblk1p4 rw console=tty0 console=ttyS0,115200 earlycon rootwait stmmaceth=chain_mode:1 selinux=0
[    0.000000] Unknown command line parameters: stmmaceth=chain_mode:1 selinux=0
[    0.000000] Dentry cache hash table entries: 1048576 (order: 11, 8388608 bytes, linear)
[    0.000000] Inode-cache hash table entries: 524288 (order: 10, 4194304 bytes, linear)
[    0.000000] mem auto-init: stack:all(pattern), heap alloc:off, heap free:off
[    0.000000] software IO TLB: mapped [mem 0x00000000fbfff000-0x00000000fffff000] (64MB)
[    0.000000] Memory: 7580644K/8386560K available (10050K kernel code, 4991K rwdata, 4096K rodata, 2197K init, 619K bss, 281628K reserved, 524288K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=4.
[    0.000000] rcu:     RCU debug extended QS entry/exit.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] CPU with hartid=0 is not available
[    0.000000] riscv-intc: unable to find hart id for /cpus/cpu@0/interrupt-controller
[    0.000000] riscv-intc: 64 local interrupts mapped
[    0.000000] plic: plic@c000000: mapped 136 interrupts with 4 handlers for 9 contexts.
[    0.000000] random: get_random_bytes called from start_kernel+0x4d6/0x6f2 with crng_init=0
[    0.000000] riscv_timer_init_dt: Registering clocksource cpuid [0] hartid [1]
[    0.000000] clocksource: riscv_clocksource: mask: 0xffffffffffffffff max_cycles: 0x1d854df40, max_idle_ns: 881590404240 ns
[    0.000001] sched_clock: 64 bits at 4MHz, resolution 250ns, wraps every 2199023255500ns
[    0.008999] clocksource: timer@13050000.ch0: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
[    0.020322] clocksource: timer@13050000.ch1: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
[    0.031644] clocksource: timer@13050000.ch2: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
[    0.042966] clocksource: timer@13050000.ch3: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 79635851949 ns
[    0.054500] Console: colour dummy device 80x25
[    0.060766] printk: console [tty0] enabled
[    0.065321] Calibrating delay loop (skipped), value calculated using timer frequency.. 8.00 BogoMIPS (lpj=40000)
[    0.076546] pid_max: default: 32768 minimum: 301
[    0.081895] Mount-cache hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    0.090386] Mountpoint-cache hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    0.100710] ASID allocator disabled
[    0.104647] rcu: Hierarchical SRCU implementation.
[    0.110099] EFI services will not be available.
[    0.115491] smp: Bringing up secondary CPUs ...
[    0.122164] smp: Brought up 1 node, 4 CPUs
[    0.128675] devtmpfs: initialized
[    0.140554] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.151421] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.172156] pinctrl core: initialized pinctrl subsystem
[    0.178825] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.186062] thermal_sys: Registered thermal governor 'step_wise'
[    0.186410] cpuidle: using governor menu
[    0.221692] platform soc:dsi-output: Fixing up cyclic dependency with 29400000.dc8200
[    0.230885] platform 295d0000.mipi: Fixing up cyclic dependency with soc:dsi-output
[    0.239739] platform 29590000.hdmi: Fixing up cyclic dependency with 29400000.dc8200
[    0.260173] HugeTLB registered 1.00 GiB page size, pre-allocated 0 pages
[    0.267558] HugeTLB registered 2.00 MiB page size, pre-allocated 0 pages
[    0.278652] vgaarb: loaded
[    0.281885] SCSI subsystem initialized
[    0.286380] usbcore: registered new interface driver usbfs
[    0.292458] usbcore: registered new interface driver hub
[    0.298413] usbcore: registered new device driver usb
[    0.304215] mc: Linux media interface: v0.10
[    0.308948] videodev: Linux video capture interface: v2.00
[    0.315198] Advanced Linux Sound Architecture Driver Initialized.
[    0.322316] Bluetooth: Core ver 2.22
[    0.326276] NET: Registered PF_BLUETOOTH protocol family
[    0.332132] Bluetooth: HCI device and connection manager initialized
[    0.339130] Bluetooth: HCI socket layer initialized
[    0.344523] Bluetooth: L2CAP socket layer initialized
[    0.350093] Bluetooth: SCO socket layer initialized
[    0.355794] clocksource: Switched to clocksource riscv_clocksource
[    0.362842] FS-Cache: Loaded
[    0.373444] NET: Registered PF_INET protocol family
[    0.379787] IP idents hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[    0.395751] tcp_listen_portaddr_hash hash table entries: 4096 (order: 5, 163840 bytes, linear)
[    0.405505] TCP established hash table entries: 65536 (order: 7, 524288 bytes, linear)
[    0.415075] TCP bind hash table entries: 65536 (order: 9, 2097152 bytes, linear)
[    0.425754] TCP: Hash tables configured (established 65536 bind 65536)
[    0.433238] UDP hash table entries: 4096 (order: 6, 393216 bytes, linear)
[    0.441300] UDP-Lite hash table entries: 4096 (order: 6, 393216 bytes, linear)
[    0.450019] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.456826] RPC: Registered named UNIX socket transport module.
[    0.463352] RPC: Registered udp transport module.
[    0.468549] RPC: Registered tcp transport module.
[    0.473725] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.481693] PCI: CLS 0 bytes, default 64
[    0.486425] Unpacking initramfs...
[    0.487015] Initialise system trusted keyrings
[    0.495255] workingset: timestamp_bits=62 max_order=21 bucket_order=0
[    0.508711] NFS: Registering the id_resolver key type
[    0.514308] Key type id_resolver registered
[    0.518953] Key type id_legacy registered
[    0.523486] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.530905] nfs4flexfilelayout_init: NFSv4 Flexfile Layout Driver Registering...
[    0.539159] ntfs: driver 2.1.32 [Flags: R/W].
[    0.544246] jffs2: version 2.2. (NAND) © 2001-2006 Red Hat, Inc.
[    0.551506] fuse: init (API version 7.34)
[    0.595623] NET: Registered PF_ALG protocol family
[    0.600961] Key type asymmetric registered
[    0.605481] Asymmetric key parser 'x509' registered
[    0.610996] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 249)
[    0.619185] io scheduler mq-deadline registered
[    0.624189] io scheduler kyber registered
[    0.732482] clk-starfive-jh7110 13020000.clock-controller: starfive JH7110 clkgen init successfully.
[    0.743970] L2CACHE: DataError @ 0x00000000.08040110
[    0.749558] L2CACHE: DataFail @ 0x00000000.0804005B
[    0.755037] L2CACHE: No. of Banks in the cache: 8
[    0.760259] L2CACHE: No. of ways per bank: 16
[    0.765075] L2CACHE: Sets per bank: 256
[    0.769333] L2CACHE: Bytes per cache block: 64
[    0.774248] L2CACHE: Index of the largest way enabled: 15
[    0.780581] jh7110-pmu 17030000.power-controller: registered 8 power domains
[    0.853955] Serial: 8250/16550 driver, 6 ports, IRQ sharing disabled
[    0.877923] loop: module loaded
[    0.883406] cadence-qspi 13010000.spi: Failed to get clk 'clk_src': -2
[    0.890677] cadence-qspi 13010000.spi: cadence_quadspi_clk_init: failed to get qspi clocks
[    0.899856] cadence-qspi: probe of 13010000.spi failed with error -2
[    0.908060] libphy: Fixed MDIO Bus: probed
[    0.914161] CAN device driver interface
[    0.919104] starfive-eth-plat 16030000.ethernet: force_sf_dma_mode is ignored if force_thresh_dma_mode is set.
[    0.930634] starfive-eth-plat 16030000.ethernet: User ID: 0x41, Synopsys ID: 0x52
[    0.938967] starfive-eth-plat 16030000.ethernet:     DWMAC4/5
[    0.945041] starfive-eth-plat 16030000.ethernet: DMA HW capability register supported
[    0.953728] starfive-eth-plat 16030000.ethernet: RX Checksum Offload Engine supported
[    0.962408] starfive-eth-plat 16030000.ethernet: Wake-Up On Lan supported
[    0.970029] starfive-eth-plat 16030000.ethernet: TSO supported
[    0.976499] starfive-eth-plat 16030000.ethernet: Enable RX Mitigation via HW Watchdog Timer
[    0.985752] starfive-eth-plat 16030000.ethernet: Enabled Flow TC (entries=1)
[    0.993563] starfive-eth-plat 16030000.ethernet: TSO feature enabled
[    1.000601] starfive-eth-plat 16030000.ethernet: Using 40 bits DMA width
[    1.341315] Freeing initrd memory: 10960K
[    1.604178] libphy: stmmac: probed
[    1.607998] YT8531 Gigabit Ethernet stmmac-0:00: attached PHY driver (mii_bus:phy_addr=stmmac-0:00, irq=POLL)
[    1.618959] YT8531 Gigabit Ethernet stmmac-0:01: attached PHY driver (mii_bus:phy_addr=stmmac-0:01, irq=POLL)
[    1.631178] starfive-eth-plat 16040000.ethernet: force_sf_dma_mode is ignored if force_thresh_dma_mode is set.
[    1.642623] starfive-eth-plat 16040000.ethernet: User ID: 0x41, Synopsys ID: 0x52
[    1.650913] starfive-eth-plat 16040000.ethernet:     DWMAC4/5
[    1.656995] starfive-eth-plat 16040000.ethernet: DMA HW capability register supported
[    1.665640] starfive-eth-plat 16040000.ethernet: RX Checksum Offload Engine supported
[    1.674298] starfive-eth-plat 16040000.ethernet: Wake-Up On Lan supported
[    1.681865] starfive-eth-plat 16040000.ethernet: TSO supported
[    1.688330] starfive-eth-plat 16040000.ethernet: Enable RX Mitigation via HW Watchdog Timer
[    1.697582] starfive-eth-plat 16040000.ethernet: Enabled Flow TC (entries=1)
[    1.705365] starfive-eth-plat 16040000.ethernet: TSO feature enabled
[    1.712388] starfive-eth-plat 16040000.ethernet: Using 40 bits DMA width
[    1.974393] libphy: stmmac: probed
[    1.978209] YT8531 Gigabit Ethernet stmmac-1:00: attached PHY driver (mii_bus:phy_addr=stmmac-1:00, irq=POLL)
[    1.989180] YT8531 Gigabit Ethernet stmmac-1:01: attached PHY driver (mii_bus:phy_addr=stmmac-1:01, irq=POLL)
[    2.001777] Intel(R) Wireless WiFi driver for Linux
[    2.009589] cdns3-starfive 10210000.usbdrd: usb mode 2 2.0 probe success
[    2.017890] usbcore: registered new interface driver uas
[    2.023811] usbcore: registered new interface driver usb-storage
[    2.046255] starfive-rtc 17040000.rtc: registered as rtc0
[    2.052242] starfive-rtc 17040000.rtc: setting system clock to 2001-01-01T00:00:00 UTC (978307200)
[    2.062315] i2c_dev: i2c /dev entries driver
[    2.067597] usbcore: registered new interface driver uvcvideo
[    2.085825] thermal thermal_zone0: failed to read out thermal zone (-110)
[    2.093976] starfive-wdt 13070000.wdog: Heartbeat: timeout=15, count/2=180000000 (0aba9500)
[    2.103774] Bluetooth: HCI UART driver ver 2.3
[    2.108711] Bluetooth: HCI UART protocol H4 registered
[    2.115110] sdhci: Secure Digital Host Controller Interface driver
[    2.121974] sdhci: Copyright(c) Pierre Ossman
[    2.126830] Synopsys Designware Multimedia Card Interface Driver
[    2.133784] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.141249] jh7110-sec 16000000.crypto: Unable to request sec_m dma channel in DMA channel
[    2.150420] jh7110-sec 16000000.crypto: Cannot initial dma chan
[    2.157267] usbcore: registered new interface driver usbhid
[    2.163435] usbhid: USB HID core driver
[    2.167931] riscv-pmu-sbi: SBI PMU extension is available
[    2.173920] riscv-pmu-sbi: 16 firmware and 4 hardware counters
[    2.180398] riscv-pmu-sbi: Perf sampling/filtering is not supported as sscof extension is not available
[    2.191175] usbcore: registered new interface driver snd-usb-audio
[    2.206853] NET: Registered PF_INET6 protocol family
[    2.213672] Segment Routing with IPv6
[    2.217779] In-situ OAM (IOAM) with IPv6
[    2.222239] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    2.229425] NET: Registered PF_PACKET protocol family
[    2.235017] can: controller area network core
[    2.239939] NET: Registered PF_CAN protocol family
[    2.245242] can: raw protocol
[    2.248536] can: broadcast manager protocol
[    2.253173] can: netlink gateway - max_hops=1
[    2.258267] Bluetooth: RFCOMM TTY layer initialized
[    2.263670] Bluetooth: RFCOMM socket layer initialized
[    2.269401] Bluetooth: RFCOMM ver 1.11
[    2.273559] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    2.279438] Bluetooth: BNEP filters: protocol multicast
[    2.285219] Bluetooth: BNEP socket layer initialized
[    2.290771] lib80211: common routines for IEEE802.11 drivers
[    2.297220] 9pnet: Installing 9P2000 support
[    2.302001] Key type dns_resolver registered
[    2.307588] Loading compiled-in X.509 certificates
[    2.350736] starfive_jh7110-pinctrl 13040000.gpio: SiFive GPIO chip registered 64 GPIOs
[    2.360374] starfive_jh7110-pinctrl 17020000.gpio: SiFive GPIO chip registered 4 GPIOs
[    2.369381] pl08xdmac 16008000.sec_dma: initialized 8 virtual memcpy channels
[    2.377302] pl08xdmac 16008000.sec_dma: initialized 16 virtual slave channels
[    2.387000] debugfs: Directory '16008000.sec_dma' with parent 'dmaengine' already present!
[    2.396196] pl08xdmac 16008000.sec_dma: DMA: PL080 rev0 at 0x16008000 irq 23
[    2.404238] ssp-pl022 10060000.spi: ARM PL022 driver for StarFive SoC platform, device ID: 0x00041022
[    2.414470] ssp-pl022 10060000.spi: mapped registers from 0x0000000010060000 to (____ptrval____)
[    2.424641] ssp-pl022 10060000.spi: Requested frequency: 10000000 Hz is unsupported,select by default 8250000 Hz
[    2.436305] ssp-pl022 10060000.spi: will use autosuspend for runtime pm, delay 100ms
[    2.446314] i2c 2-0045: Fixing up cyclic dependency with 295d0000.mipi
[    2.453799] seeed_panel 2-0045: Unknown Atmel firmware revision: 0x00
[    2.461148] tinker_ft5406 2-0038: Address = 0x38
[    2.466264] tinker_ft5406 2-0038: width = 800, height = 480, reverse = 1
[    2.473800] tinker_ft5406 2-0038: i2c read error, -121
[    2.479496] tinker_ft5406 2-0038: Checking touch ic failed
[    2.485556] tinker_ft5406: probe of 2-0038 failed with error -121
[    2.492497] i2c 2-0019: Fixing up cyclic dependency with 295d0000.mipi
[    2.500631] Goodix-TS 2-0014: supply AVDD28 not found, using dummy regulator
[    2.508579] Goodix-TS 2-0014: supply VDDIO not found, using dummy regulator
[    2.635952] Goodix-TS 2-0014: i2c test failed attempt 1: -121
[    2.675952] Goodix-TS 2-0014: i2c test failed attempt 2: -121
[    2.715816] Goodix-TS 2-0014: I2C communication failure: -121
[    2.722335] Goodix-TS: probe of 2-0014 failed with error -121
[    2.729643] at24 5-0050: supply vcc not found, using dummy regulator
[    2.737476] at24 5-0050: 512 byte 24c04 EEPROM, writable, 16 bytes/write
[    2.746836] axp15060-regulator 5-0036: Register mipi_0p9 done! vol range:900 ~ 900 mV
[    2.756980] axp15060-regulator 5-0036: Register hdmi_1p8 done! vol range:1800 ~ 1800 mV
[    2.766440] axp15060-regulator 5-0036: Register sdio_vdd done! vol range:0 ~ 0 mV
[    2.776198] axp15060-regulator 5-0036: Register hdmi_0p9 done! vol range:900 ~ 900 mV
[    2.785416] axp15060-regulator 5-0036: Register vcc_3v3 done! vol range:0 ~ 0 mV
[    2.795124] axp15060-regulator 5-0036: Register cpu_vdd done! vol range:500 ~ 1540 mV
[    2.804630] i2c 6-0010: Fixing up cyclic dependency with 19800000.vin_sysctl
[    2.812858] imx219 6-0010: supply VANA not found, using dummy regulator
[    2.820338] imx219 6-0010: supply VDIG not found, using dummy regulator
[    2.827752] imx219 6-0010: supply VDDL not found, using dummy regulator
[    2.849769] imx219 6-0010: failed to read chip id 219
[    2.855552] imx219: probe of 6-0010 failed with error -5
[    2.864136] pcie_plda 2b000000.pcie: Failed to get reset-gpio.
[    2.870627] pcie_plda 2b000000.pcie: Init gpio failed
[    2.876229] pcie_plda: probe of 2b000000.pcie failed with error -22
[    2.885936] pcie_plda 2c000000.pcie: Failed to get reset-gpio.
[    2.892388] pcie_plda 2c000000.pcie: Init gpio failed
[    2.898003] pcie_plda: probe of 2c000000.pcie failed with error -22
[    2.919513] clk-starfive-jh7110-vout 295c0000.clock-controller: starfive JH7110 clk_vout init successfully.
[    2.942184] clk-starfive-jh7110-isp 19810000.clock-controller: starfive JH7110 clk_isp init successfully.
[    2.953480] dw_axi_dmac_platform 16050000.dma-controller: DesignWare AXI DMA Controller, 4 channels
[    2.964582] printk: console [ttyS0] disabled
[    2.989558] 10000000.serial: ttyS0 at MMIO 0x10000000 (irq = 17, base_baud = 1500000) is a 16550A
[    2.999434] printk: console [ttyS0] enabled
[    2.999434] printk: console [ttyS0] enabled
[    3.008247] printk: bootconsole [uart0] disabled
[    3.008247] printk: bootconsole [uart0] disabled
[    3.018650] jh7110-vin 19800000.vin_sysctl: stfcamss probe enter!
[    3.026884] jh7110-vin 19800000.vin_sysctl: stfcamss probe success!
[    3.044291] dwmmc_starfive 16010000.sdio0: IDMAC supports 32-bit address mode.
[    3.044579] dwmmc_starfive 16020000.sdio1: IDMAC supports 32-bit address mode.
[    3.051630] dwmmc_starfive 16010000.sdio0: Using internal DMA controller.
[    3.051674] jh7110-sec 16000000.crypto: will run requests pump with realtime priority
[    3.054017] jh7110-sec 16000000.crypto: Initialized
[    3.054774] starfive-i2s 120b0000.i2stx_4ch0:  designware: play supported
[    3.054780] starfive-i2s 120b0000.i2stx_4ch0: designware: i2s master mode supported
[    3.054893] sf-mipi-dphy-tx 295e0000.mipi-dphy: sf_dphy_probe begin
[    3.054899] sf-mipi-dphy-tx 295e0000.mipi-dphy: ===> sf_dphy_probe enter, 445
[    3.054979] sf-mipi-dphy-tx 295e0000.mipi-dphy: control ECO
[    3.054991] sf-mipi-dphy-tx 295e0000.mipi-dphy: supply mipi_1p8 not found, using dummy regulator
[    3.055184] sf-mipi-dphy-tx 295e0000.mipi-dphy: sf_dphy_probe end
[    3.055302] cdns-dsi 295d0000.mipi: dsi_sys_clk = 297000000
[    3.055437] cdns-dsi 295d0000.mipi: starfive dsi bind end
[    3.056802] of_cfs_init
[    3.056826] of_cfs_init: OK
[    3.057148] starfive-pwmdac 100b0000.pwmdac: clk_apb0 = 49500000, clk_pwmdac_apb = 49500000, clk_pwmdac_core = 4068493
[    3.057436] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    3.058834] dwmmc_starfive 16020000.sdio1: Using internal DMA controller.
[    3.065623] dwmmc_starfive 16010000.sdio0: Version ID is 290a
[    3.073480] dwmmc_starfive 16020000.sdio1: Version ID is 290a
[    3.073521] dwmmc_starfive 16020000.sdio1: DW MMC controller at irq 30,32 bit host data width,32 deep fifo
[    3.078407] dwmmc_starfive 16010000.sdio0: DW MMC controller at irq 29,32 bit host data width,32 deep fifo
[    3.085299] mmc_host mmc1: card is polling.
[    3.092930] mmc_host mmc0: card is non-removable.
[    3.170928] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    3.214809] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[    3.223467] cfg80211: failed to load regulatory.db
[    3.315902] mmc_host mmc1: Bus speed (slot 0) = 198000000Hz (slot req 400000Hz, actual 399193HZ div = 248)
[    3.385919] mmc_host mmc0: Bus speed (slot 0) = 198000000Hz (slot req 400000Hz, actual 399193HZ div = 248)
[    3.569239] mmc_host mmc1: Bus speed (slot 0) = 198000000Hz (slot req 50000000Hz, actual 49500000HZ div = 2)
[    3.579384] mmc1: new high speed SDHC card at address 0007
[    3.586676] mmcblk1: mmc1:0007 SD32G 29.0 GiB
[    3.605601]  mmcblk1: p1 p2 p3 p4
[    3.612164] starfive soc:display-subsystem: bound 29400000.dc8200 (ops 0xffffffff80e7b1d0)
[    3.620479] innohdmi-starfive 29590000.hdmi: inno hdmi bind begin
[    3.627840] innohdmi-starfive 29590000.hdmi: [drm:inno_hdmi_bind] *ERROR* cannot get hpd gpio property
[    3.637189] Kernel BUG [#1]
[    3.639989] Modules linked in:
[    3.643050] CPU: 2 PID: 1 Comm: swapper/0 Not tainted 5.15.0+ #2
[    3.649060] Hardware name: StarFive VisionFive V2 (DT)
[    3.654202] epc : _regulator_put+0x14a/0x14e
[    3.658483]  ra : regulator_put+0x26/0x3c
[    3.662498] epc : ffffffff8040c95e ra : ffffffff8040c988 sp : ffffffd00400b9e0
[    3.669735]  gp : ffffffff815045a8 tp : ffffffe0bff40000 t0 : ffffffd00400b648
[    3.676963]  t1 : 0000000000000002 t2 : 0000000000000000 s0 : ffffffd00400ba10
[    3.684200]  s1 : ffffffe0c30efa80 a0 : ffffffe0c30efa80 a1 : 0000000000000115
[    3.691437]  a2 : 0000000000000000 a3 : ffffffe1f8999590 a4 : 0000000000000000
[    3.698673]  a5 : 0000000000000001 a6 : 0000000200000022 a7 : ffffffe0c30eaf40
[    3.705910]  s2 : ffffffff814a3348 s3 : ffffffe0c0638810 s4 : ffffffd00400ba48
[    3.713147]  s5 : 0000000000000009 s6 : ffffffe0c2804000 s7 : fffffffffffffffe
[    3.720383]  s8 : ffffffff814adbb8 s9 : 0000000000000000 s10: 0000000000000000
[    3.727620]  s11: 0000000000000000 t3 : 0000000007200720 t4 : 0000000000000001
[    3.734856]  t5 : ffffffff81044448 t6 : 6720647068207465
[    3.740172] status: 0000000200000120 badaddr: 0000000000000000 cause: 0000000000000003
[    3.748105] [<ffffffff8040c95e>] _regulator_put+0x14a/0x14e
[    3.753685] [<ffffffff8040c988>] regulator_put+0x26/0x3c
[    3.759000] [<ffffffff80411534>] devm_regulator_release+0xe/0x16
[    3.765011] [<ffffffff804a6dbc>] devres_release_group+0xa2/0x102
[    3.771024] [<ffffffff8049b65e>] component_bind_all+0xdc/0x1b6
[    3.776866] [<ffffffff80495794>] vs_drm_bind+0x76/0x112
[    3.782101] [<ffffffff8049b83a>] try_to_bring_up_master+0x102/0x140
[    3.788377] [<ffffffff8049bb88>] component_master_add_with_match+0xc4/0x104
[    3.795347] [<ffffffff804956ae>] vs_drm_platform_probe+0x12c/0x19c
[    3.801536] [<ffffffff804a516c>] platform_probe+0x4e/0x92
[    3.806940] [<ffffffff804a2f7c>] really_probe.part.0+0x66/0x232
[    3.812867] [<ffffffff804a31b8>] __driver_probe_device+0x70/0xde
[    3.818877] [<ffffffff804a3252>] driver_probe_device+0x2c/0xb0
[    3.824718] [<ffffffff804a37aa>] __driver_attach+0x60/0xf4
[    3.830211] [<ffffffff804a0ec8>] bus_for_each_dev+0x6e/0xae
[    3.835789] [<ffffffff804a2874>] driver_attach+0x1a/0x22
[    3.835806] mmc_host mmc0: Bus speed (slot 0) = 198000000Hz (slot req 300000Hz, actual 300000HZ div = 330)
[    3.841104] [<ffffffff804a2308>] bus_add_driver+0xe6/0x198
[    3.841110] [<ffffffff804a3fe2>] driver_register+0x50/0xe4
[    3.841116] [<ffffffff804a4ede>] __platform_driver_register+0x1c/0x24
[    3.868179] [<ffffffff80a21ada>] vs_drm_init+0x34/0x56
[    3.873325] [<ffffffff8000210c>] do_one_initcall+0x4e/0x178
[    3.878905] [<ffffffff80a00f7c>] kernel_init_freeable+0x1a8/0x20a
[    3.885005] [<ffffffff809cb766>] kernel_init+0x1e/0x104
[    3.890237] [<ffffffff80003178>] ret_from_exception+0x0/0xc
[    3.895850] ---[ end trace d8bf584a996f34f9 ]---
[    3.900477] Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b
[    3.908148] SMP: stopping secondary CPUs
[    3.912083] ---[ end Kernel panic - not syncing: Attempted to kill init! exitcode=0x0000000b ]---

**Comment by MichaelZhuxx** [comment]
let me guess what have you done, just you want to add a new kernel(tag:3.0.4) to boot debian image(202303), right? if so, you also need add/replace a new dtb file

**Comment by st3g4n0** [comment]
> 

That’s right! Any manual to change the current dtbs?
