### ISSUE TITLE
Add nautilus (and more) to the default image

### ISSUE THREAD

**Issue by danboid** [starfive-tech/VisionFive2#62]
I know starfive-jh7110-202306-nvme-minimal-desktop.img is called minimal for a reason but its a bit TOO minimal, especially considering how painfully slow the unstable rv64 Debian repo is.

`nautilus` should be included so that users have a file manager and can easily (un)mount and access disks. It makes no sense to install GNOME but not its file manager too. 

I would also suggest adding Firefox, VLC and ffmpeg (a dependency of VLC) to the default desktop image. How many users with their VF2 connected to a display aren't going to want a web browser? Not many.

I would prefer that Libreoffice and nodejs weren't included in the minimal image as they're not minimal apps.

**Comment by ThomasKorimort** [comment]
https://rvspace.org/en/project/VisionFive2_Debian_User_Guide lists in section 4.3.3. how to install additional packages for Multimedia and Browsing:

Some packages particular are not available to download via apt/apt-get, and is provided by StarFive, which includes (as of June 2023):

    Node.js 18.0.0
    v8 10.2.154.13
    libsdl2-dev
    QT 5.15.2
    Firefox 105.0
    Libreoffice 7.5
    NW.js
    FFmpeg
    GStreamer
    v4l2test (This is a custom shell script to use the CSI camera)
    Chromium 103
    VLC 3.0.18

 

Debian Repo for StarFive Packages: [Github Link](https://github.com/starfive-tech/Debian/)

`wget https://github.com/starfive-tech/Debian/releases/download/v0.8.0-engineering-release-wayland/install_package_and_dependencies.sh
chmod +x install_package_and_dependencies.sh
sudo ./install_package_and_dependencies.sh`

The GNOME system can be updated to a reasonable amount of packages including file browser by installing the gnome-core package:

`sudo apt install gnome-core` in the Debian-202306 image

You should also install gnome-shell-extension-manager:

`sudo apt install gnome-shell-extension-manager` if you want shell extensions like Dash-to-Dock and many others, as the Browser support for GNOME Shell extensions is basically not working.

The Debian-202306 version is Debian 12 sid, the unstable version of Bookworm as it has riscv architecture support integrated, whereas  only Debian 13 Trixie will officially support riscv architecture. Thus till the next two years Debian 12 sid will be the distribution, on which the StarFive Debian images will be based on. Currently still a lot of basic driver support has to be done for the StarFive VisionFive 2 kernel supplied with the StarFive Debian images. USB subsystem support is lacking (e.g. for Ethernet over USB), the nftables firewall is not working...

**Comment by danboid** [comment]
Thanks for adding these packages to the minimal image!
