### ISSUE TITLE
ERROR: No hash found for gcc-12.2.0.tar.xz

### ISSUE THREAD

**Issue by xugaoxiang** [starfive-tech/VisionFive2#66]
ubuntu 18.04 64bit
SDK JH7110_VisionFive2_devel branch

"ERROR: No hash found for gcc-12.2.0.tar.xz" occurred when make -j$(nproc), I use the command sha512sum, calculate the downloaded file, hash value is equal to the value in file buildroot/package/gcc/gcc.hash.

Even NOT work when delete the gcc tar file and remake. git-lfs  has been installed.

Thanks.

**Comment by andyhu-stf** [comment]
Please try to run make again, maybe your network environment issue.

Buildroot will first try to download the gcc-12.2.0.tar.xz from http://ftpmirror.gnu.org, the download link is 
http://ftpmirror.gnu.org/gcc/gcc-12.2.0/gcc-12.2.0.tar.xz
You can run `wget http://ftpmirror.gnu.org/gcc/gcc-12.2.0/gcc-12.2.0.tar.xz` to check your network

If download failed 3 times, then buildroot will try to download from  buildroot backup site: http://sources.buildroot.net
