### ISSUE TITLE
wifi dongle delivered with VisionFive2

### ISSUE THREAD

**Issue by dtometzki** [starfive-tech/VisionFive2#7]
Hello,

i got a wifi dongle delivered with my VisonFive2 . And now the question is how i get work this dongle. Need i do anything additional ?

my output of dmesg on my visonfive2: 

[214767.263948] usb 3-7: new high-speed USB device number 16 using xhci_hcd
[214767.390622] usb 3-7: New USB device found, idVendor=3452, idProduct=6600, bcdDevice= 0.01
[214767.390633] usb 3-7: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[214767.390637] usb 3-7: Product: 6600U
[214767.390639] usb 3-7: Manufacturer: ESWIN
[214767.390641] usb 3-7: SerialNumber: 6600U
[214776.85

**Comment by martin-zs** [comment]
Looks like the driver is here: https://github.com/eswincomputing/eswin_6600u/

**Comment by dtometzki** [comment]
Hi martin-zs,

i have a lot of errors when i try to build it

**Comment by dtometzki** [comment]
Hello,

is there an wifi dongle that works with the sdk available ?

Many Thanks
Damian

**Comment by andyhu-stf** [comment]
Hi @dtometzki , the wifi dongle firmware and driver we will be released on next version

**Comment by dtometzki** [comment]
Hello @andyhu-stf,

when is the next version planed ? Is a faster download link available for download ? Is it a dialup link or what is it ?https://debian.starfivetech.com/VisionFive2/Engineering%20Release/Image-55/starfive-jh7110-VF2-VF2_515_v2.3.0-55.img.bz2

Best regards
Damain

**Comment by MichaelZhuxx** [comment]
@dtometzki thanks for your interest, we will implement this dongle in SDK first then move to Debian. hopefully we could release it in Jan. 2023. Stay tuned
