### ISSUE TITLE
Internal compiler error: Error reporting routines re-entered

### ISSUE THREAD

**Issue by yoyojacky** [starfive-tech/VisionFive2#8]
` GEN     Makefile
  CALL    /home/jacky/VisionFive2/linux/scripts/checksyscalls.sh
  CALL    /home/jacky/VisionFive2/linux/scripts/atomic/check-atomics.sh
  CHK     include/generated/compile.h
  CC      drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.o
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1846:2: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
 1846 |  &PMRLockSysPhysAddressesLocalMem,
      |  ^
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1846:2: note: (near initialization for '_sPMRLMAFuncTab')
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1846:2: error: invalid initializer
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1846:2: note: (near initialization for '_sPMRLMAFuncTab.<anonymous>')
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1848:2: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
 1848 |  &PMRUnlockSysPhysAddressesLocalMem,
      |  ^
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1848:2: note: (near initialization for '_sPMRLMAFuncTab')
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1848:2: error: initialization of 'PVRSRV_ERROR (*)(void *, IMG_DEVMEM_OFFSET_T,  IMG_UINT8 *, size_t,  size_t *)' {aka 'enum PVRSRV_ERROR_TAG (*)(void *, long long unsigned int,  unsigned char *, long unsigned int,  long unsigned int *)'} from incompatible pointer type 'PVRSRV_ERROR (*)(void *)' {aka 'enum PVRSRV_ERROR_TAG (*)(void *)'} [-Werror=incompatible-pointer-types]
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1848:2: note: (near initialization for '_sPMRLMAFuncTab.pfnReadBytes')
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1850:2: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
 1850 |  &PMRSysPhysAddrLocalMem,
      |  ^
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1850:2: note: (near initialization for '_sPMRLMAFuncTab')
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1850:2: error: initialization of 'PVRSRV_ERROR (*)(void *, size_t,  size_t,  void **, void **, PMR_FLAGS_T)' {aka 'enum PVRSRV_ERROR_TAG (*)(void *, long unsigned int,  long unsigned int,  void **, void **, long long unsigned int)'} from incompatible pointer type 'PVRSRV_ERROR (*)(void *, IMG_UINT32,  IMG_UINT32,  IMG_DEVMEM_OFFSET_T *, IMG_BOOL *, IMG_DEV_PHYADDR *)' {aka 'enum PVRSRV_ERROR_TAG (*)(void *, unsigned int,  unsigned int,  long long unsigned int *, enum tag_img_bool *, IMG_DEV_PHYADDR *)'} [-Werror=incompatible-pointer-types]
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1850:2: note: (near initialization for '_sPMRLMAFuncTab.pfnAcquireKernelMappingData')
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1852:2: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
 1852 |  &PMRAcquireKernelMappingDataLocalMem,
      |  ^
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1852:2: note: (near initialization for '_sPMRLMAFuncTab')
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1852:2: error: initialization of 'void (*)(void)' from incompatible pointer type 'PVRSRV_ERROR (*)(void *, size_t,  size_t,  void **, void **, PMR_FLAGS_T)' {aka 'enum PVRSRV_ERROR_TAG (*)(void *, long unsigned int,  long unsigned int,  void **, void **, long long unsigned int)'} [-Werror=incompatible-pointer-types]
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1852:2: note: (near initialization for '_sPMRLMAFuncTab.pfnReleasePMRFactoryLock')
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1854:2: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
 1854 |  &PMRReleaseKernelMappingDataLocalMem,
      |  ^
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1854:2: note: (near initialization for '_sPMRLMAFuncTab')
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1854:2: error: initialization of 'PVRSRV_ERROR (*)(void *)' {aka 'enum PVRSRV_ERROR_TAG (*)(void *)'} from incompatible pointer type 'void (*)(void *, void *)' [-Werror=incompatible-pointer-types]
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1854:2: note: (near initialization for '_sPMRLMAFuncTab.pfnUnpinMem')
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1856:2: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
 1856 |  &PMRReadBytesLocalMem,
      |  ^
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1856:2: note: (near initialization for '_sPMRLMAFuncTab')
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1858:2: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
 1858 |  &PMRWriteBytesLocalMem,
      |  ^
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1858:2: note: (near initialization for '_sPMRLMAFuncTab')
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1858:2: error: initialization of 'PVRSRV_ERROR (*)(void *, const PMR *, IMG_UINT64,  IMG_UINT32,  IMG_UINT32 *, IMG_UINT32,  IMG_UINT32 *)' {aka 'enum PVRSRV_ERROR_TAG (*)(void *, const struct _PMR_ *, long long unsigned int,  unsigned int,  unsigned int *, unsigned int,  unsigned int *)'} from incompatible pointer type 'PVRSRV_ERROR (*)(void *, IMG_DEVMEM_OFFSET_T,  IMG_UINT8 *, size_t,  size_t *)' {aka 'enum PVRSRV_ERROR_TAG (*)(void *, long long unsigned int,  unsigned char *, long unsigned int,  long unsigned int *)'} [-Werror=incompatible-pointer-types]
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1858:2: note: (near initialization for '_sPMRLMAFuncTab.pfnChangeSparseMemCPUMap')
In file included from /home/jacky/VisionFive2/linux/include/uapi/linux/posix_types.h:5,
                 from /home/jacky/VisionFive2/linux/include/uapi/linux/types.h:14,
                 from /home/jacky/VisionFive2/linux/include/linux/types.h:6,
                 from /home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/include/img_types.h:69,
                 from /home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:45:
/home/jacky/VisionFive2/linux/include/linux/stddef.h:8:14: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
    8 | #define NULL ((void *)0)
      |              ^
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1860:2: note: in expansion of macro 'NULL'
 1860 |  NULL,
      |  ^~~~
/home/jacky/VisionFive2/linux/include/linux/stddef.h:8:14: note: (near initialization for '_sPMRLMAFuncTab')
    8 | #define NULL ((void *)0)
      |              ^
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1860:2: note: in expansion of macro 'NULL'
 1860 |  NULL,
      |  ^~~~
/home/jacky/VisionFive2/linux/include/linux/stddef.h:8:14: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
    8 | #define NULL ((void *)0)
      |              ^
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1862:2: note: in expansion of macro 'NULL'
 1862 |  NULL,
      |  ^~~~
/home/jacky/VisionFive2/linux/include/linux/stddef.h:8:14: note: (near initialization for '_sPMRLMAFuncTab')
    8 | #define NULL ((void *)0)
      |              ^
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1862:2: note: in expansion of macro 'NULL'
 1862 |  NULL,
      |  ^~~~
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1864:2: error: positional initialization of field in 'struct' declared with 'designated_init' attribute [-Werror=designated-init]
 1864 |  &PMRChangeSparseMemLocalMem,
      |  ^
/home/jacky/VisionFive2/linux/drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.c:1864:2: note: (near initialization for '_sPMRLMAFuncTab')
'PVRSRV_ERROR (*)(void *, PMR_MAPPING_TABLE *)
Internal compiler error: Error reporting routines re-entered.
0x7f222bf1a082 __libc_start_main
        ../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://bugs.buildroot.net/> for instructions.
make[7]: *** [/home/jacky/VisionFive2/linux/scripts/Makefile.build:277: drivers/gpu/drm/img/img-rogue/services/server/common/physmem_lma.o] Error 1
make[6]: *** [/home/jacky/VisionFive2/linux/scripts/Makefile.build:540: drivers/gpu/drm/img/img-rogue] Error 2
make[5]: *** [/home/jacky/VisionFive2/linux/scripts/Makefile.build:540: drivers/gpu/drm/img] Error 2
make[4]: *** [/home/jacky/VisionFive2/linux/scripts/Makefile.build:540: drivers/gpu/drm] Error 2
make[3]: *** [/home/jacky/VisionFive2/linux/scripts/Makefile.build:540: drivers/gpu] Error 2
make[2]: *** [/home/jacky/VisionFive2/linux/Makefile:1868: drivers] Error 2
make[2]: Leaving directory '/home/jacky/VisionFive2/work/linux'
make[1]: *** [Makefile:219: __sub-make] Error 2
make[1]: Leaving directory '/home/jacky/VisionFive2/linux'
make: *** [Makefile:218: /home/jacky/VisionFive2/work/linux/vmlinux] Error 2
`
* OS: Ubuntu 20.04.3 
How to sovle this issue?

**Comment by yoyojacky** [comment]
seems like " http://sources.buildroot.net/linux-JH7110_VisionFive2_devel-br1.tar.gz " Not Found .

**Comment by yoyojacky** [comment]
`jacky@Dev1:~/VisionFive2$ !make
make -j$(nproc)
make -C /home/jacky/VisionFive2/buildroot RISCV=/home/jacky/VisionFive2/work/buildroot_initramfs/host O=/home/jacky/VisionFive2/work/buildroot_initramfs
make[1]: Entering directory '/home/jacky/VisionFive2/buildroot'
>>> linux-headers JH7110_VisionFive2_devel Downloading
GIT_DIR=/home/jacky/VisionFive2/buildroot/dl/linux/git/.git git init .
Reinitialized existing Git repository in /home/jacky/VisionFive2/buildroot/dl/linux/git/.git/
GIT_DIR=/home/jacky/VisionFive2/buildroot/dl/linux/git/.git git remote set-url origin 'git@github.com:starfive-tech/linux.git'
Fetching all references
GIT_DIR=/home/jacky/VisionFive2/buildroot/dl/linux/git/.git git fetch origin
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Detected a corrupted git cache.
Removing it and starting afresh.
GIT_DIR=/home/jacky/VisionFive2/buildroot/dl/linux/git/.git git init .
Initialized empty Git repository in /home/jacky/VisionFive2/buildroot/dl/linux/git/.git/
GIT_DIR=/home/jacky/VisionFive2/buildroot/dl/linux/git/.git git remote add origin 'git@github.com:starfive-tech/linux.git'
GIT_DIR=/home/jacky/VisionFive2/buildroot/dl/linux/git/.git git remote set-url origin 'git@github.com:starfive-tech/linux.git'
Fetching all references
GIT_DIR=/home/jacky/VisionFive2/buildroot/dl/linux/git/.git git fetch origin
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Detected a corrupted git cache.
This is the second time in a row; bailing out
wget --passive-ftp -nd -t 3 -O '/home/jacky/VisionFive2/work/buildroot_initramfs/build/.linux-JH7110_VisionFive2_devel-br1.tar.gz.mpaYN1/output' 'http://sources.buildroot.net/linux/linux-JH7110_VisionFive2_devel-br1.tar.gz'
--2022-12-20 14:42:54--  http://sources.buildroot.net/linux/linux-JH7110_VisionFive2_devel-br1.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.26.1.37, 104.26.0.37, 172.67.72.56, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.26.1.37|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-20 14:42:55 ERROR 404: Not Found.

wget --passive-ftp -nd -t 3 -O '/home/jacky/VisionFive2/work/buildroot_initramfs/build/.linux-JH7110_VisionFive2_devel-br1.tar.gz.5sr4h7/output' 'http://sources.buildroot.net/linux-JH7110_VisionFive2_devel-br1.tar.gz'
--2022-12-20 14:42:55--  http://sources.buildroot.net/linux-JH7110_VisionFive2_devel-br1.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 172.67.72.56, 104.26.0.37, 104.26.1.37, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|172.67.72.56|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-20 14:42:55 ERROR 404: Not Found.
`

**Comment by andyhu-stf** [comment]
@yoyojacky , the buildroot need to download linux again for the linux header which is required by the riscv gcc toolchain.
it seem you have problem when downloading "git clone git@github.com:starfive-tech/linux.git". You need to add ssh public key to your github account for it using the git ssh.

like #6

**Comment by yoyojacky** [comment]
problem solved by editing :  /home/user/VisionFive2/buildroot/dl/linux/git/.git/config 
from "git@github.com:starfive-tech/linux.git" to "https://github.com/starfive-tech/linux.git"
