### ISSUE TITLE
I cannot upgrade to 5.10.3

### ISSUE THREAD

**Issue by liberodark** [starfive-tech/VisionFive2#88]
Hi,

I can flash `visionfive2_fw_payload` in `/dev/mtd1`
```
flashcp -v visionfive2_fw_payload.img /dev/mtd1
visionfive2_fw_payload.img won't fit into /dev/mtd1!
```
Best Regards

**Comment by varyhin** [comment]
https://github.com/starfive-tech/VisionFive2/issues/73

**Comment by liberodark** [comment]
`flashcp -v visionfive2_fw_payload.img /dev/mtd2` (that fix my issue)

```
cat /proc/mtd 
dev:    size   erasesize  name
mtd0: 00040000 00001000 "spl"
mtd1: 00010000 00001000 "uboot-env"
mtd2: 00300000 00001000 "uboot"
mtd3: 00100000 00001000 "data"
```

Thanks you that strange because have upgrade to [3.8.2](https://github.com/starfive-tech/VisionFive2/releases/tag/VF2_v3.8.2) on mtd1 without any issue.

Best Regards
