### ISSUE TITLE
VisionFive2 Build error

### ISSUE THREAD

**Issue by COthello** [starfive-tech/VisionFive2#90]
Hi，
When I build VersionFive2， I got an error message like following， could anyone help to fix it？Thanks.
![versionfive](https://github.com/starfive-tech/VisionFive2/assets/9839536/176ad4b2-9177-4a11-a39f-31e35fefe5aa)

**Comment by andyhu-stf** [comment]
We can't reproduce your issue. From your log, it seem that you had removed work/buildroot_initramfs/build/host-ncurses-6.1/.stamp_patched and then you just rebuild it again.
or you can try build the host-ncurses package:

> make -C ./work/buildroot_initramfs/ O=./work/buildroot_initramfs host-ncurses-dirclean
> make -C ./work/buildroot_initramfs/ O=./work/buildroot_initramfs host-ncurses-rebuild

**Comment by COthello** [comment]
> make -C ./work/buildroot_initramfs/ O=./work/buildroot_initramfs host-ncurses-rebuild

thank you，it works.
