### ISSUE TITLE
compile linux kernel error

### ISSUE THREAD

**Issue by wjh-study** [starfive-tech/VisionFive2#94]
make[2]: 进入目录“/mnt/disk/wjh/code/VisionFive2/VisionFive2/work/linux”
  GEN     Makefile
  HOSTCC  scripts/dtc/yamltree.o
  HOSTLD  scripts/dtc/fdtoverlay
/mnt/disk/wjh/code/VisionFive2/VisionFive2/linux/scripts/dtc/yamltree.c:9:10: fatal error: yaml.h: 没有那个文件或目录
    9 | #include <yaml.h>
      |          ^~~~~~~~
compilation terminated.
make[3]: *** [/mnt/disk/wjh/code/VisionFive2/VisionFive2/linux/scripts/Makefile.host:112：scripts/dtc/yamltree.o] 错误 1
make[3]: *** 正在等待未完成的任务....
make[2]: *** [/mnt/disk/wjh/code/VisionFive2/VisionFive2/linux/Makefile:1427：scripts_dtc] 错误 2
make[2]: 离开目录“/mnt/disk/wjh/code/VisionFive2/VisionFive2/work/linux”
make[1]: *** [Makefile:219：__sub-make] 错误 2
make[1]: 离开目录“/mnt/disk/wjh/code/VisionFive2/VisionFive2/linux”
make: *** [Makefile:213：/mnt/disk/wjh/code/VisionFive2/VisionFive2/work/linux/vmlinux] 错误 2
when I use make -j20,it has some error

**Comment by wjh-study** [comment]
May I ask if there is an IMG package that can be downloaded directly?

**Comment by flyingcys** [comment]
sudo apt-get install libyaml-dev

**Comment by andyhu-stf** [comment]
This issue could be fixed through as @flyingcys. Now close it
